Neos:
  Neos:
    modules:
      management:
        submodules:
          themeCssVariables:
            label: 'Theme Css Variable'
            controller: 'Theme\CssVariables\Module\Controller\BackendController'
            description: 'Manage the colors of your theme by overriding the css variables'
            icon: 'fas fa-palette'
            additionalResources:
              styleSheets:
                - 'resource://Theme.CssVariables/Public/main.css'
              javaScripts:
                - 'resource://Theme.CssVariables/Public/main.js'
    fusion:
      autoInclude:
        Theme.CssVariables: true

Theme:
  CssVariables:
    # You can choose whatever name you like, but make sure it ends with .css
    stylesheetName: 'custom.css'
    # Array of types that are allowed in the backend module
    # Please be aware that breakpoints can be extremely dangerous when not using the CSS custom property
    # consistently
    types:
      - color
#      - font
#      - breakpoints
#      - other
    excludedPackages:
      - Neos
      - Yoast
